// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPs5Ay28ghlRNwv7NywZ9PtkOdVI3qGNU',
    appId: '1:459396175528:web:83031288b9daacb17b149d',
    messagingSenderId: '459396175528',
    projectId: 'crashaid-a1d3c',
    authDomain: 'crashaid-a1d3c.firebaseapp.com',
    databaseURL: 'https://crashaid-a1d3c-default-rtdb.firebaseio.com',
    storageBucket: 'crashaid-a1d3c.firebasestorage.app',
    measurementId: 'G-02490LT9QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpJw6BXvjwpQb_oqxaREa8t-txiOLjQE',
    appId: '1:459396175528:android:b2cc5292945020f57b149d',
    messagingSenderId: '459396175528',
    projectId: 'crashaid-a1d3c',
    databaseURL: 'https://crashaid-a1d3c-default-rtdb.firebaseio.com',
    storageBucket: 'crashaid-a1d3c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFUlcGhmAsbjClzEI_WqYTHar28nXzKw',
    appId: '1:459396175528:ios:2059b32a2bfef6907b149d',
    messagingSenderId: '459396175528',
    projectId: 'crashaid-a1d3c',
    databaseURL: 'https://crashaid-a1d3c-default-rtdb.firebaseio.com',
    storageBucket: 'crashaid-a1d3c.firebasestorage.app',
    androidClientId: '459396175528-5fma7ackffnq7b2g4erkkk2l2um1ofkh.apps.googleusercontent.com',
    iosClientId: '459396175528-inebf61uioelb7vkuf4v8ofsq4acnclv.apps.googleusercontent.com',
    iosBundleId: 'com.example.crashaid',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvFUlcGhmAsbjClzEI_WqYTHar28nXzKw',
    appId: '1:459396175528:ios:2059b32a2bfef6907b149d',
    messagingSenderId: '459396175528',
    projectId: 'crashaid-a1d3c',
    databaseURL: 'https://crashaid-a1d3c-default-rtdb.firebaseio.com',
    storageBucket: 'crashaid-a1d3c.firebasestorage.app',
    androidClientId: '459396175528-5fma7ackffnq7b2g4erkkk2l2um1ofkh.apps.googleusercontent.com',
    iosClientId: '459396175528-inebf61uioelb7vkuf4v8ofsq4acnclv.apps.googleusercontent.com',
    iosBundleId: 'com.example.crashaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPs5Ay28ghlRNwv7NywZ9PtkOdVI3qGNU',
    appId: '1:459396175528:web:a5ae7ae3b7c5e5eb7b149d',
    messagingSenderId: '459396175528',
    projectId: 'crashaid-a1d3c',
    authDomain: 'crashaid-a1d3c.firebaseapp.com',
    databaseURL: 'https://crashaid-a1d3c-default-rtdb.firebaseio.com',
    storageBucket: 'crashaid-a1d3c.firebasestorage.app',
    measurementId: 'G-NLTGMSSQBF',
  );
}
